### PR TITLE
Upgrade guava dependency to v30.0-jre

### PR DESCRIPTION
**Pull request by majk-p**
First of all thanks for providing this great project!
With this PR I want to bump guava. In my project I'm using Snyk vulnerability scanner, that revealed following security issue with current version of `minio-java`:

```
Issues with no direct upgrade or patch:
  ✗ Information Disclosure [Medium Severity][https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-1015415] in com.google.guava:guava@29.0-jre
    introduced by MY_LIBRARY@SOME_VERSION > MY_MINIO_WRAPPER@SOME_VERSION > io.minio:minio@8.2.1 > com.google.guava:guava@29.0-jre
  This issue was fixed in versions: 30.0-android, 30.0-jre
```
More details on Guava vulnerability: https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-1015415

### CODE REVIEW

**Comment by majk-p** [comment]
@harshavardhana @vadmeste can you please have a look?

**Review by balamurugana — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by majk-p** [comment]
Thank you for merging! Can we please have this released?

**Comment by majk-p** [comment]
@harshavardhana @balamurugana when can we see this released?

**Comment by harshavardhana** [comment]
> @harshavardhana @balamurugana when can we see this released?

Soon @majk-p

**Pull request merged**
