### PR TITLE
fix: handle SSE in copyObject() properly and have one source code.

### PR DESCRIPTION
**Pull request by balamurugana**
Added new version of copyObject(). Note: this method makes source and
destination argument swapping correctly to denote on which bucket and
object the request is sent.
    
```
public void copyObject(String bucketName, String objectName, Map<String,String> headerMap, ServerSideEncryption sse,
                       String srcBucketName, String srcObjectName, ServerSideEncryption srcSse,
                       CopyConditions copyConditions)
```

### CODE REVIEW

**Comment by sinhaashish** [comment]
Build issue
File	Line	: `minio-java/api/src/main/java/io/minio/MinioClient.java`
Line Number : `1309`
Problem : `These nested if statements could be combined`

**Comment by kannappanr** [comment]
@balamurugana I see changes to getObject API. Can you please change the commit title and the message to reflect the changes ?

**Comment by kannappanr** [comment]
I believe Readme.md also should be updated

**Comment by balamurugana** [comment]
Depends on https://github.com/minio/minio-java/pull/775 https://github.com/minio/minio-java/pull/776

**Comment by kannappanr** [comment]
ping @aead @sinhaashish

**Comment by kannappanr** [comment]
ping @sinhaashish

**Comment by kannappanr** [comment]
ping @sinhaashish

**Pull request merged**
