### PR TITLE
add stream support for request body

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Comment by harshavardhana** [comment]
https://ci.appveyor.com/project/harshavardhana/minio-java/build/111 - looks like tests failed.

**Comment by balamurugana** [comment]
:-1: doing some changes to avoid UnsupportedEncodingException

**Comment by balamurugana** [comment]
all the changes are done wrt character encoding

**Comment by harshavardhana** [comment]
> all the changes are done wrt character encoding

Cool, seems like build issue.

**Comment by balamurugana** [comment]
:-1: need to fix with partsize calculation and multipart resume

**Comment by balamurugana** [comment]
all the changes are done.  travis failure may be due to older ubuntu/java version.

**Pull request merged**
