### PR TITLE
fixes trace output, location query and single http client object

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Comment by balamurugana** [comment]
:-1: i am writing tracing with network interceptor

**Comment by harshavardhana** [comment]
> i am writing tracing with network interceptor

+1 okhttp does this internally, if you enable it it will log the request and response headers properly,

**Comment by harshavardhana** [comment]
Is this ready to be merged?

**Comment by balamurugana** [comment]
As there is a limitation to pass tracestream to interceptor, i will address this feature separately.  Please review this patch

**Pull request merged**
