### PR TITLE
Add restoreObject API support

### PR DESCRIPTION
**Pull request by balamurugana**
Signed-off-by: Bala.FA <bala@minio.io>

### CODE REVIEW

**Review by harshavardhana — COMMENTED** [review]
PTAL @krisis @poornas

**Comment by harshavardhana** [comment]
PTAL @krisis @poornas

**Review by poornas — APPROVED** [review]
LGTM

**Comment by poornas** [comment]
Build failures @balamurugana

**Review by krisis — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
