### PR TITLE
[WIP]: add support for server-side encryption and GET/PUT options.

### LINKED ISSUE #660: Set metadata for encrypted object (putObject())
Hello,

I'm running a local instance of minio server and i wrote some basic java code leveraging "minio-java 3.0.11" to store an encrypted object on it.

```
//Recreates secret key from environment variable
SecretKeySpec secretKey = new SecretKeySpec(Hex.decodeHex("MY_AES_KEY_IN_HEX".toCharArray()),"AES");

//Encrypts file and uploads it
FileInputStream uploadStream = new FileInputStream(/path/to/my/file);

client.putObject("test","object",uploadStream,uploadStream.available(), "application/octet-stream", secretKey);
```

This is working just fine.
The problem is that i now want to associate some metadata to this blob. Something like:

```
HashMap<String,String> map = new HashMap<String,String>();
map.put("MY_KEY","MY_VALUE");

```
As far as i can tell there's no call to perform this. Or is there?

### LINKED ISSUE #666: SSE-C on Java SDK
Hello,

I the newly SSE-C implementation on Minio server, no issue to upload file with SSE-C encryption from with go SDK but I don't find nothing to do that with Java SDK (put or get).
Not yet released ?

### PR DESCRIPTION
**Pull request by aead**
This change does the following:
 - Remove legacy code for client-side encryption
  The class `Crypto.java` was removed completely 
 - Add native support for server-side encryption (SSE-C, SSE-S3)
  containing GET, PUT, COPY.
  Therefore the new class `ServerSideEncryption.java` is added.
 - Add GET/PUT options concept to make usage of encryption (and other GET/PUT features) 
  more convenient for clients. 
  Therefore the classes `Options.java`, `GetOptions.java` and `PutOptions.java` are added.
 - Unit tests are updated
 - Functional tests are updated 

Things that are not done yet (but should be added):
 - TLS and V4 checks if SSE-C or SSE-KMS is used.
-  Stat- and Copy Options.
 - API documentation

Fixes #666
Fixes #660

### CODE REVIEW

**Comment by harshavardhana** [comment]
@aead is this PR ready?

**Comment by HoaBo** [comment]
@aead Is this good to go?

**Comment by deekoder** [comment]
Can we close this as stale

**Comment by aead** [comment]
Closing. This PR does too much. We should keep the concept of `ServerSideEncryption.java` but the other refactoring should be addressed differently (and cleanly)...

**Pull request closed without merging**
