### PR TITLE
Mint - Avoid invalid JSON output

### PR DESCRIPTION
**Pull request by iternity-dotcom**
## Description

The console outputs have been removed.

 

## Motivation and Context

Testing with Mint Suite generates a log.json file. We want to process the file, but MinIO Java generates invalid JSON.

 

## How to test this PR?

Running the tests against a `minio server data{1...4}` should now return a valid JSON.

 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Optimization (provides speedup with no functional changes)

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

 

## Checklist:

- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)

- [ ] Documentation updated

- [ ] Unit tests added/updated

### CODE REVIEW

**Comment by balamurugana** [comment]
Run functional test like below instead of changing current behavior
```
FunctionalTest <ENDPOINT> <ACCESSKEY> <SECRETKEY> <REGION>
```

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by balamurugana — CHANGES_REQUESTED** [review]
Run functional test like below instead of changing current behavior
```
FunctionalTest <ENDPOINT> <ACCESSKEY> <SECRETKEY> <REGION>
```

**Comment by vadmeste** [comment]
> Run functional test like below instead of changing current behavior
> 
> ```
> FunctionalTest <ENDPOINT> <ACCESSKEY> <SECRETKEY> <REGION>
> ```

Oh downloadMinio() is not executed during functional tests ?

**Comment by balamurugana** [comment]
> > Run functional test like below instead of changing current behavior
> > ```
> > FunctionalTest <ENDPOINT> <ACCESSKEY> <SECRETKEY> <REGION>
> > ```
> 
> Oh downloadMinio() is not executed during functional tests ?

It is called if not those four arguments are passed.

**Comment by iternity-dotcom** [comment]
@balamurugana: So this call has to be changed somewhere else? I don‘t quite understand.

**Comment by balamurugana** [comment]
@iternity-dotcom The functional test can be run in two ways
1. Without any arguments
  - it downloads `minio` server and runs with fixed configuration for functional tests to run
2. With arguments
  - functional tests run against on provided S3 endpoint.

If you are using functional tests on `mint`, you would need to run your own s3 server and run functional tests against that.

**Comment by iternity-dotcom** [comment]
Thanks @balamurugana for your explanation.
We run the mint tests against our own Minio instance and observe the above behavior.
The functional minio-java tests are implicitly called by mint. So maybe this is a problem on how functional tests are called by mint?

@andrebruch Can you also share your thoughts on this?

**Comment by iternity-dotcom** [comment]
@andrebruch Maybe we are missing the <REGION> param?

**Comment by iternity-dotcom** [comment]
@balamurugana Another question: Why does it make sense to write the removed console outputs to log.json in case the functional tests are called without params (thus downloading the Minio automatically)? Wouldn't this also result in an invalid log.json?

**Comment by andrebruch** [comment]
@balamurugana For us the 2nd way is relevant.
With this way no invalid JSON is actually generated.

@iternity-dotcom The 1st way was called by a change on my part in `mint`:
I passed the `RUN_ON_FAIL` variable as an environment variable and additionally (that was the mistake) as a parameter to minio-java.

I corrected the RUN_ON_FAIL-PR: https://github.com/minio/minio-java/pull/1180.
So it is correct that this PR is closed.

**Comment by balamurugana** [comment]
@iternity-dotcom 

> @balamurugana Another question: Why does it make sense to write the removed console outputs to log.json in case the functional tests are called without params (thus downloading the Minio automatically)? Wouldn't this also result in an invalid log.json?

Result as JSON is outputted only if `MINT_MODE` env is set i.e. JSON output is relevant to mint only. May be you could send a fix to error out if four arguments are not passed if `MINT_MODE` env is set.

**Comment by iternity-dotcom** [comment]
@balamurugana OK. Thanks for concluding the conversation here.

**Pull request closed without merging**
