### PR TITLE
Fix typo in JavaDoc

### PR DESCRIPTION
**Pull request by everflux**

### CODE REVIEW

**Comment by deekoder** [comment]
@balamurugana do you know why travis fails on this typo correction pr

**Comment by balamurugana** [comment]
@deekoder As per travis log, there was connection reset i.e. some network issue.  I strongly recommend to check travis logs when failed. If such errors, restart failed jobs.

**Comment by deekoder** [comment]
We did restart it.

**Comment by deekoder** [comment]
Actually we did it 4 times. There is some other issue that needs investigation. Blocking this PR to help diagnose this issue.
screenshot from 2018-05-15 13-00-55

**Pull request merged**
